blobon/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf import settings
from django.contrib import admin
from punns.views import UserFeed
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from accounts.forms import Blobon_loginForm
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^accounts/login/$', 'accounts.views.custom_login'),
    url(r'^accounts/blobon_login/$', 'accounts.views.blobon_login'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
                          {'next_page': '/'}),
    url(r'^login/$', 'django.contrib.auth.views.login', 
                          {'template_name': 'login.html', 'authentication_form':Blobon_loginForm}),
    url(r'^settings/profile/$', 'accounts.views.edit_profile'),
    url(r'^settings/password/$', 'django.contrib.auth.views.password_change',
                          {'post_change_redirect': '/settings/password/password_reset_confirmation/'}),
    url(r'^settings/password/password_reset_confirmation/$', 'django.contrib.auth.views.password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', 
                          {'template_name': 'registration/password_reset_form.html',
                           'email_template_name': 'registration/password_reset_email.html'}),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', 
			  {'template_name': 'registration/password_reset_done.html'}),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', 
                          {'template_name': 'registration/password_reset_confirm.html'}),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', 
			  {'template_name': 'registration/password_reset_complete.html'}),
    url(r'^$', 'blogs.views.index'),
    url(r'^pics/$', 'blogs.views.pics'),
    #url(r'^videos/$', 'blogs.views.videos'),
    url(r'^new/$', 'punns.views.new'),
    url(r'^moderate/$', 'punns.views.moderate'),
    url(r'^twitter/$', 'accounts.views.twitter'),
    url(r'^twitter-success/$', 'accounts.views.twitter_success'),
    url(r'^news/$', 'news.views.all'),
    url(r'^earnings/$', 'earnings.views.index'),
    url(r'^createblog/$', 'blogs.views.createblog'),
    url(r'^newpost/(?P<slug>.*)/$', 'blogs.views.newpost'),
    url(r'^newsubuser/(?P<slug>.*)/$', 'blogs.views.new_subuser'),
    url(r'^subscribe/(?P<slug>.*)/$', 'blogs.views.subscribe_to_infoletter'),
    url(r'^savedraft/(?P<slug>.*)/$', 'blogs.views.savedraft'),
    url(r'^newcategory/(?P<slug>.*)/$', 'blogs.views.newcategory'),
    url(r'^newsubcat/(?P<id>.*)/$', 'blogs.views.add_sub_category'),
    url(r'^addsubcat/(?P<id>.*)/$', 'blogs.views.newcategorysub'),
    url(r'^newrss/(?P<slug>.*)/$', 'blogs.views.newrss'),
    url(r'^newemail/(?P<slug>.*)/$', 'blogs.views.create_info_email'),
    url(r'^page/(?P<slug>.*)/$', 'blogs.views.page'),
    url(r'^(?P<year>\d{4})/$', 'blogs.views.year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', 'blogs.views.month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'blogs.views.day_archive'),
    url(r'^viewexpense/(?P<year>\d{4})/$', 'books.views.viewexpense_year'),
    url(r'^viewexpense/(?P<year>\d{4})/(?P<month>\d{2})/$', 'books.views.viewexpense_month'),
    url(r'^viewexpense/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'books.views.viewexpense_day'),
    url(r'^createpage/(?P<slug>.*)/$', 'blogs.views.createpage'),
    url(r'^converttag/(?P<id>.*)/$', 'blogs.views.converttag'),
    url(r'^convertcategory/(?P<id>.*)/$', 'blogs.views.convertcategory'),
    url(r'^dashboard/$', 'blogs.views.dashboard'),
    url(r'^dashboard/(?P<slug>.*)/$', 'blogs.views.administrateblog'),
    url(r'^administrateposts/(?P<slug>.*)/$', 'blogs.views.administrateposts'),
    url(r'^queue/(?P<slug>.*)/$', 'blogs.views.queue'),
    url(r'^published/(?P<slug>.*)/$', 'blogs.views.published'),
    url(r'^publishedcomments/(?P<slug>.*)/$', 'blogs.views.publishedcomments'),
    url(r'^translation/(?P<slug>.*)/$', 'blogs.views.translation'),
    url(r'^quicktranslation/(?P<id>.*)/$', 'blogs.views.quicktranslation'),
    url(r'^translatepost/(?P<id>.*)/$', 'blogs.views.translatepost'),
    url(r'^billing/(?P<id>.*)/$', 'books.views.invoice'),
    url(r'^administratepages/(?P<slug>.*)/$', 'blogs.views.administratepages'),
    url(r'^administratecomments/(?P<slug>.*)/$', 'blogs.views.administratecomments'),
    url(r'^administratecategories/(?P<slug>.*)/$', 'blogs.views.administratecategories'),
    url(r'^custompost/(?P<slug>.*)/$', 'blogs.views.custom_post'),
    url(r'^rss_auto/(?P<slug>.*)/$', 'blogs.views.rss_auto_post'),
    url(r'^administrateemails/(?P<slug>.*)/$', 'blogs.views.administrateemails'),
    url(r'^administratetags/(?P<slug>.*)/$', 'blogs.views.administratetags'),
    url(r'^administratemodel/(?P<slug>.*)/(?P<id>.*)/$', 'blogs.views.administratemodel'),
    url(r'^editmodeldata/(?P<slug>.*)/(?P<id>.*)/$', 'blogs.views.editmodeldata'),
    url(r'^deletemodeldata/(?P<slug>.*)/(?P<id>.*)/$', 'blogs.views.deletemodeldata'),
    url(r'^contributors/(?P<slug>.*)/$', 'blogs.views.administratecontributor'),
    url(r'^administratesettings/(?P<slug>.*)/$', 'blogs.views.administratesettings'),
    url(r'^editprofile/$', 'blogs.views.editprofile'),
    url(r'^editcontributor/(?P<id>.*)/(?P<slug>.*)/$', 'blogs.views.editcontributor'),
    url(r'^deletecontributor/(?P<id>.*)/(?P<slug>.*)/$', 'blogs.views.deletecontributor'),
    url(r'^deletecustom/(?P<id>.*)/$', 'blogs.views.deletecustom'),
    url(r'^deletefield/(?P<id>.*)/$', 'blogs.views.deletefield'),
    url(r'^editcustom/(?P<id>.*)/$', 'blogs.views.editcustom'),
    url(r'^adddata/(?P<id>.*)/$', 'blogs.views.adddata'),
    url(r'^editpost/(?P<id>.*)/$', 'blogs.views.editpost'),
    url(r'^editpage/(?P<id>.*)/$', 'blogs.views.editpage'),
    url(r'^fastedit/(?P<slug>.*)/$', 'blogs.views.fastedit'),
    url(r'^fasteditpost/(?P<id>.*)/$', 'blogs.views.fasteditpost'),    
    url(r'^editemail/(?P<id>.*)/$', 'blogs.views.editemail'),
    url(r'^previewemail/(?P<id>.*)/$', 'blogs.views.view_info_letter'),
    url(r'^editcategory/(?P<id>.*)/$', 'blogs.views.editcategory'),
    url(r'^edittag/(?P<id>.*)/$', 'blogs.views.edittag'),
    url(r'^approve/(?P<id>.*)/$', 'blogs.views.approvecomment'),
    url(r'^create/$', 'punns.views.create'),
    url(r'^contactblog/(?P<slug>.*)/$', 'blogs.views.contactblog'),
    url(r'^contact/$', 'blogs.views.contact'),
    url(r'^password/(?P<slug>.*)/$', 'blogs.views.password'),
    url(r'^passwordsingle/(?P<id>.*)/$', 'blogs.views.passwordsingle'),
    url(r'^newcomment/(?P<id>.*)/$', 'blogs.views.newcomment'),
    url(r'^signalcomment/(?P<id>.*)/$', 'blogs.views.signalcomment'),
    url(r'^entreprise/$', 'blogs.views.entreprise'),
    url(r'^send/(?P<id>.*)/$', 'blogs.views.send_email_now'),
    url(r'^create-from-rss/$', 'punns.views.create_from_rss'),
    url(r'^createcat/$', 'punns.views.createcat'),
    url(r'^createalbum/$', 'punns.views.createalbum'),
    url(r'^universal/$', 'punns.views.universal'),
    url(r'^cate/(?P<slug>.*)/$', 'punns.views.cat'),
    url(r'^cat/(?P<slug>.*)/$', 'blogs.views.category'),
    url(r'^tag/(?P<slug>.*)/$', 'blogs.views.tag'),
    url(r'^c/(?P<slug>.*)/$', 'blogs.views.category_main'),
    url(r'^a/(?P<username>.*)/$', 'blogs.views.author'),
    url(r'^delete/(?P<id>.*)/$', 'comments.views.delete'),
    url(r'^deleteuser/$', 'blogs.views.deleteuser'),
    url(r'^punn-delete/(?P<id>.*)/$', 'punns.views.delete'),
    url(r'^deletepost/(?P<id>.*)/$', 'blogs.views.deletepost'),
    url(r'^deletepost_trans/(?P<id>.*)/$', 'blogs.views.deletepost_trans'),
    url(r'^deletepage/(?P<id>.*)/$', 'blogs.views.deletepage'),
    url(r'^deletecategory/(?P<id>.*)/$', 'blogs.views.deletecategory'),
    url(r'^deletetag/(?P<id>.*)/$', 'blogs.views.deletetag'),
    url(r'^deleterss/(?P<id>.*)/$', 'blogs.views.deleterss'),
    url(r'^publishnow/(?P<id>.*)/$', 'blogs.views.publish_now'),
    url(r'^publishpagenow/(?P<id>.*)/$', 'blogs.views.publish_page_now'),
    url(r'^deletecomment/(?P<id>.*)/$', 'blogs.views.deletecomment'),
    url(r'^deletecommentsingle/(?P<id>.*)/$', 'blogs.views.deletecomment_from_single'),
    url(r'^deletecommentspending/(?P<slug>.*)/$', 'blogs.views.delete_pending_comments'),
    url(r'^deletesubscription/(?P<id>.*)/$', 'blogs.views.deletesubscription'),
    url(r'^deleteemail/(?P<id>.*)/$', 'blogs.views.deleteemail'),
    url(r'^deleteblog/(?P<slug>.*)/$', 'blogs.views.deleteblog'),
    url(r'^hot/(?P<id>.*)/$', 'punns.views.hot'),
    url(r'^up/(?P<id>.*)/$', 'votes.views.up'),
    url(r'^down/(?P<id>.*)/$', 'votes.views.down'),
    url(r'^comment-up/(?P<id>.*)/$', 'votes.views.commentup'),
    url(r'^comment-down/(?P<id>.*)/$', 'votes.views.commentdown'),
    url(r'^reblog/(?P<id>.*)/$', 'punns.views.reblog'),
    url(r'^favorite/(?P<id>.*)/$', 'punns.views.favorite'),
    url(r'^p/(?P<shorturl>.*)/$', 'blogs.views.single'),
    url(r'^a/(?P<shorturl>.*)/$', 'punns.views.album'),
    url(r'^privacy/$', direct_to_template, { 'template': 'privacy.html' }),
    url(r'^tos/$', direct_to_template, { 'template': 'tos.html' }),
    url(r'^opinion/$', direct_to_template, { 'template': 'opinion.html' }),
    url(r'^closed/$', direct_to_template, { 'template': 'closed.html' }),
    url(r'^privacypolicy/$', direct_to_template, { 'template': 'privacypolicy.html' }),
    url(r'^terms/$', direct_to_template, { 'template': 'terms.html' }),
    url(r'^totb/$', direct_to_template, { 'template': 'totb.html' }),

blobon/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from datetime import datetime

import os

STATUS = (
    ('Se', 'Sent'),
    ('Dr', 'Draft'),
    ('Su', 'Submission'),
    ('Pa', 'Paid'),
)

def get_file_path_receipt(instance, filename):
    ext = filename.split('.')[-1]
    prefix = filename.split('.')[0]
    variable = ('receipt')
    filename = "%s_%s.%s" % (prefix, variable, ext)
    return os.path.join('', filename)

class Client(models.Model):
    organization_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=100, blank=True)
    street_adress = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    postal_code = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        return self.organization_name

class Invoice(models.Model):
    author = models.ForeignKey(User)
    client = models.ForeignKey(Client)
    date_of_issue = models.DateTimeField(default=datetime.now, blank=True)
    invoice_number = models.PositiveIntegerField(blank=True)
    terms = models.CharField(max_length=1000)
    sub_notes = models.CharField(max_length=1000, blank=True)
    sub_description = models.TextField(max_length=10000, blank=True)
    paid_notes = models.CharField(max_length=1000, blank=True)
    notes = models.CharField(max_length=1000)    
    created = models.DateTimeField(auto_now_add = True)
    last_modified = models.DateTimeField(auto_now = True,  null=True, blank=True)
    status = models.CharField(max_length=2, choices=STATUS, default="Dr", null=True)
    with_items = models.BooleanField(default=True) 
    with_taxes = models.BooleanField(default=True)
    def __unicode__(self):
        return unicode(self.invoice_number)

class Project(models.Model):
    name = models.CharField(max_length=50)
    client = models.ForeignKey(Client)
    rate_per_hour = models.DecimalField(max_digits=5, decimal_places=2)
    def __unicode__(self):
        return u'%s - %s' % (self.name, self.client)

class Tax(models.Model):
    name = models.CharField(max_length=20)
    number = models.PositiveIntegerField()
    rate = models.DecimalField(max_digits=4, decimal_places=2, blank=True)
    compound_tax = models.BooleanField(default=False)
    gouv_number = models.CharField(max_length=100, null=True, blank=True)
    def __unicode__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=50)
    project = models.ForeignKey(Project)
    rate_per_hour = models.DecimalField(max_digits=5, decimal_places=2)
    def __unicode__(self):
        return u'%s -  %s' % (self.name, self.project)

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=140)
    def __unicode__(self):
        return self.name  
  
class Vendor(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=140)
    def __unicode__(self):
        return self.name

class Expense(models.Model):
    author = models.ForeignKey(User)
    vendor = models.ForeignKey(Vendor, null=True, blank=True, default=None)
    client = models.ForeignKey(Client, null=True, blank=True, default=None)
    category = models.ForeignKey(Category, null=True, blank=True, default=None)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    date = models.DateField(auto_now_add = False)
    receipt = models.FileField(verbose_name=_("receipt"), upload_to=get_file_path_receipt, null=True, blank=True)
    notes = models.CharField(max_length=1000, null=True, blank=True)
    taxes = models.ManyToManyField(Tax, null=True, blank=True)
    def __unicode__(self):
        return u'%s - %s - %s' % (self.date, self.category, self.amount)

class Time(models.Model):
    task = models.ForeignKey(Task, null=True, blank=True)
    notes = models.CharField(max_length=1000, blank=True, default=None)
    rate_per_hour = models.DecimalField(max_digits=5, decimal_places=2)
    time = models.DecimalField(max_digits=5, decimal_places=2,blank=True)
    invoice = models.ForeignKey(Invoice, null=True, blank=True)
    #add taxes
    def __unicode__(self):
        return u'%s -  %s - %s' % (self.task, self.notes, self.id)

class Item(models.Model):
    name = models.CharField(max_length=50)
    cost = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(blank=True)
    client = models.ForeignKey(Client, null=True)
    description = models.CharField(max_length=1000, blank=True)
    def __unicode__(self):
        return u'%s - %s' % (self.name, self.client)

class Report(models.Model):
    date = models.DateTimeField(auto_now_add = True)
    start_date = models.DateTimeField(auto_now_add = False)
    end_date = models.DateTimeField(auto_now_add = False)
    author = models.ForeignKey(User)
    client = models.ForeignKey(Client, null=True, blank=True, default=None)
    vendor = models.ForeignKey(Vendor, null=True, blank=True, default=None)
    category = models.ForeignKey(Category, null=True, blank=True, default=None)
    invoice = models.BooleanField(default=False)
    expense = models.BooleanField(default=False)
    taxes = models.BooleanField(default=False)
    timesheet = models.BooleanField(default=False)
    def __unicode__(self):
        return u'%s - %s - %s' % (self.author, self.date, self.id)

blobon/news/models.py
from django.db import models
from django.utils.translation import ugettext as _

class Post(models.Model):
    title = models.CharField(max_length=140)
    content = models.TextField(max_length=10000, blank=True)
    #Datetime infos
    created = models.DateTimeField(auto_now_add = True)
    pub_date = models.DateTimeField(auto_now_add = True, null=True, blank=True)
    last_modified = models.DateTimeField(auto_now = True,  null=True, blank=True)
    #Media
    def __unicode__(self):
        return self.title
    @models.permalink
    def get_absolute_url(self):
        return ('news.views.news', [str(self.id)])

blobon/blogs/templates/administrateemails.html
{% extends "administrateblog.html" %}
{% load i18n %}
{% load url from future %}
    {% block additional-css %}
    <style>
      textarea {
        resize: none;
      }
      .edit_buttons {
        padding: 10px;0px;5px;0px;
      }
    </style>
  {% endblock %}
  {% block dashboard-active %}{% endblock %}
  {% block emails-active %}class="active"{% endblock %}
  {% block content %}
          <div class="panel panel-primary" id="new_email_form" style="display: none">
            <div class="panel-heading">{% trans "Create a new email :" %}</div>
            <div class="panel-body">
              <form enctype="multipart/form-data" id="newemail" role="form" method="post" action="{% url 'blogs.views.create_info_email' blog.slug %}">{% csrf_token %}
                <div class="form-group">
                 <div style="padding-bottom:5px;"><b>{% trans "Email purpose" %}</b></div>      
                  {{ form.name}}
                </div>
                <div class="form-group">
                 {{ form.subject.label_tag }} 
                 {{ form.subject }}
                </div>
                <div class="form-group">
                 {{ form.message.label_tag }}
                  {{ form.message }}
                </div>
                <div class="form-group">
                 {{ form.status.label_tag }}
                  {{ form.status }}
                </div>
                <div class="form-group" style="display:none;">
                 {{ form.frequency.label_tag }}
                  {{ form.frequency }}
                </div>
                <div class="form-group">
                 {{ form.subscribers.label_tag }}
                  {{ form.subscribers }}
                </div>
              </form>
              <button id="submitemail" class="btn btn-primary btn-xs" disabled="disabled" title="{% trans "Save your new email" %}"><span class="glyphicon glyphicon-ok-circle"></span> {% trans "Save" %}</button>
              <span id="cancel_new_email" title="{% trans "Cancel new mailing list" %}" class="glyphicon glyphicon-remove-circle pull-right"></span>
            </div> 
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">{% trans "Info-letters" %}<a href="#" class="btn btn-default btn-xs pull-right" id="add_new_email" title="{% trans "Create a new mailing list" %}">{% trans "Create new" %}</a></div>
            {% if info_emails %}
            <table class="table table-striped">
              <colgroup>
                <col class="col-xs-6">
                <col class="col-xs-2">
                <col class="col-xs-2">
              </colgroup>
              <thead>
                <tr>
                  <th>{% trans "Email purpose" %}</th>
                  <th>{% trans "Subject" %}</th>
                  <th>{% trans "Who" %}</th>
                </tr>
              </thead>
              <tbody>
              {% for info_email in info_emails %}
                <tr>
                  <td>{{ info_email.name }}
                    <div class="edit_buttons">
                      <a href="{% url 'blogs.views.editemail' info_email.id %}" class="btn btn-default btn-xs edit_post" title="{% trans "Modify this mailing list" %}"><span class="glyphicon glyphicon-edit"></span> {% trans "Edit" %}</a>
                      <a href="#" class="btn btn-default btn-xs delete_post" title="{% trans "Delete this mailing list" %}" data-toggle="modal" data-target="#{{ info_email.id }}"><span class="glyphicon glyphicon-remove"></span> {% trans "Delete" %}</a>
                      <a href="{% url 'blogs.views.view_info_letter' info_email.id %}" target="_blank" class="btn btn-default btn-xs view_post" title="{% trans "View email content" %}"><span class="glyphicon glyphicon-new-window"></span> {% trans "View email" %}</a>
                      <a href="{% url 'blogs.views.send_email_now' info_email.id %}" class="btn btn-default btn-xs edit_post" title="{% trans "Send this mailing list now" %}"><span class="glyphicon glyphicon-send"></span> {% trans "Send now" %}</a>
                    </div>
                  </td>
                  <td>{{ info_email.subject }}</td>
                  <td>{{ info_email.get_subscribers_display }}</td>
                </tr>
  


  <div class="modal fade" id="{{ info_email.id }}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">{% trans "Delete mailing list" %}</h4>
        </div>
        <div class="modal-body">
          <p>{% trans "Are you sure you want to delete this mailing list : " %}{{ info_email.name }}</p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal">{% trans "No" %}</button>
          <a href="{% url 'blogs.views.deleteemail' info_email.id %}" class="btn btn-danger">{% trans "Yes, I Want to Delete it" %}</a>
        </div>
      </div>
    </div>
  </div>
  


            {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div class="panel-body">
            {% trans "This blog has no mailing list" %}
            </div>
            {% endif %}
          </div>


          <div class="panel panel-default">
            <div class="panel-heading" style="min-height:52px;">
             <div class="row">
              <div class="col-sm-4">
              {% trans "Blog subscribers" %}
              </div>              
              <div class="col-sm-6 col-sm-offset-2">
               <form class="form-inline" enctype="multipart/form-data" id="newsubs" role="form" method="post" action="{% url 'blogs.views.subscribe_to_infoletter' blog.slug %}">{% csrf_token %}
               <b>{% trans "Add new : " %}</b>
                <div class="form-group">
                 {{ subs_form.email}}
                </div>
                 <button id="subscribe_submit" value="subs_admin" name="subs_admin"type="submit" disabled="disabled"class="btn btn-primary btn-sm">{% trans "Add" %}</button>
               </form>
              </div>
             </div>
    <script>
      $(document).ready(function(){
        $('#id_email').change(function() {
        if($(this).val() != '') {
          $('#subscribe_submit').prop("disabled", false);
          }
        else {
          $('#subscribe_submit').prop("disabled", true);
        }
        });
      });
    </script>
            </div>
            {% if subscriptions%}
            <table class="table table-striped">
              <colgroup>
                <col class="col-xs-7">
                <col class="col-xs-2">
                <col class="col-xs-1">
              </colgroup>
              <thead>
                <tr>
                  <th>{% trans "Email" %}</th>
                  <th>{% trans "New" %}</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              {% for subscription in subscriptions %}
                <tr>
                  <td>{{ subscription.email }}
                  </td>
                  <td>{{ subscription.is_new }}</td>
                  <td><a href="#" class="deletesubscriber pull-left" id="deletesubscriber" title="{% trans "Delete this subscriber" %}" data-toggle="modal" data-target="#{{ subscription.id }}"><button type="button" class="close">&times;</button></td>
                </tr>

  <div class="modal fade" id="{{ subscription.id }}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">{% trans "Delete subscriber" %}</h4>
        </div>
        <div class="modal-body">
          <p>{% trans "Are you sure you want to delete this subscriber?" %}</p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal">{% trans "No" %}</button>
          <a href="{% url 'blogs.views.deletesubscription' subscription.id %}" class="btn btn-danger">{% trans "Yes, I Want to Delete it" %}</a>
        </div>
      </div>
    </div>
  </div>

            {% endfor %}

              </tbody>
            </table>
            {% else %}
            <div class="panel-body">
            {% trans "This blog has no subscriber" %}
            </div>
            {% endif %}
          </div>
    <script type="text/javascript">
      $(function () {
        $('#add_new_email').tooltip({container: 'body'});
        $('#cancel_new_email').tooltip({container: 'body'});
        $('#submitemail').tooltip({container: 'body'});
      });
    </script>

    <script>
      $(document).ready(function() {
        setTimeout(function() { 
         $(".mceNoEditor").removeAttr("style");
        },10);
                   });
         
    </script>

    <script>
      $('#add_new_email').click(function() {
        $('#add_new_email').hide();
        $('#new_email_form').show();
      });
    </script>

    <script>
      $('#cancel_new_email').click(function() {
        $('#add_new_email').show();
        $('#new_email_form').hide();
        $('#newemail').each(function(){
          this.reset();
        });
      });
    </script>

    <script>
      $(document).ready(function(){
        $('#id_name').keyup(function() {
        if($(this).val() != '' && $('#id_subject').val() != '' & $('#id_content').val() != '') {
          $('#submitemail').prop("disabled", false);
          }
        else {
          $('#submitemail').prop("disabled", true);
        }
        });
      });
    </script>

    <script>
      $(document).ready(function(){
        $('#id_subject').keyup(function() {
        if($(this).val() != '' && $('#id_name').val() != '' & $('#id_content').val() != '') {
          $('#submitemail').prop("disabled", false);
          }
        else {
          $('#submitemail').prop("disabled", true);
        }
        });
      });
    </script>

    <script>
      $(document).ready(function(){
        $('#id_content').keyup(function() {
        if($(this).val() != '' && $('#id_subject').val() != '' & $('#id_name').val() != '') {
          $('#submitemail').prop("disabled", false);
          }
        else {
          $('#submitemail').prop("disabled", true);
        }
        });
      });
    </script>
    <script>
      $('#submitemail').click(function() {
        $('#newemail').submit();
      });
    </script>
    <script type="text/javascript">
      $(function () {
        $(".edit_post").tooltip({container: 'body', placement: 'bottom'});
        $(".delete_post").tooltip({container: 'body', placement: 'bottom'});
        $(".view_post").tooltip({container: 'body', placement: 'bottom'});
        $(".deletesubscriber").tooltip({container: 'body'});

      });
    </script>
  {% endblock %}